/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrackId = IDL.Nat;
export const StreamingLibrary = IDL.Record({
  'name' : IDL.Text,
  'placeholderConnected' : IDL.Bool,
});
export const MixId = IDL.Nat;
export const Timestamp = IDL.Int;
export const MixMetadata = IDL.Record({
  'id' : MixId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'duration' : IDL.Nat,
  'tracks' : IDL.Vec(TrackId),
  'createdAt' : Timestamp,
});
export const TrackMetadata = IDL.Record({
  'id' : TrackId,
  'bpm' : IDL.Opt(IDL.Nat),
  'key' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'importedAt' : Timestamp,
  'filePath' : IDL.Text,
  'artist' : IDL.Text,
  'energy' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SharingPreferences = IDL.Record({
  'shareExpiration' : IDL.Opt(Timestamp),
  'allowPublicAccess' : IDL.Bool,
  'allowDownload' : IDL.Bool,
});
export const DeckState = IDL.Record({
  'bpm' : IDL.Opt(IDL.Nat),
  'currentTrack' : IDL.Opt(TrackId),
  'isPlaying' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateBpmAdjustment' : IDL.Func(
      [TrackId, TrackId],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'connectToStreamingLibrary' : IDL.Func([StreamingLibrary], [], []),
  'deleteMix' : IDL.Func([MixId], [], []),
  'deleteTrack' : IDL.Func([TrackId], [], []),
  'getAllMixes' : IDL.Func([], [IDL.Vec(MixMetadata)], ['query']),
  'getAllMixesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MixMetadata)],
      ['query'],
    ),
  'getAllTracks' : IDL.Func([], [IDL.Vec(TrackMetadata)], ['query']),
  'getAllTracksForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TrackMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSharingPreferences' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SharingPreferences)],
      ['query'],
    ),
  'getStreamingLibraries' : IDL.Func(
      [],
      [IDL.Vec(StreamingLibrary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importTrack' : IDL.Func([TrackMetadata], [TrackId], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'ping' : IDL.Func([], [Timestamp], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDeckState' : IDL.Func([DeckState], [], []),
  'saveMix' : IDL.Func([MixMetadata], [MixId], []),
  'setSharingPreferences' : IDL.Func([SharingPreferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrackId = IDL.Nat;
  const StreamingLibrary = IDL.Record({
    'name' : IDL.Text,
    'placeholderConnected' : IDL.Bool,
  });
  const MixId = IDL.Nat;
  const Timestamp = IDL.Int;
  const MixMetadata = IDL.Record({
    'id' : MixId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'duration' : IDL.Nat,
    'tracks' : IDL.Vec(TrackId),
    'createdAt' : Timestamp,
  });
  const TrackMetadata = IDL.Record({
    'id' : TrackId,
    'bpm' : IDL.Opt(IDL.Nat),
    'key' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'importedAt' : Timestamp,
    'filePath' : IDL.Text,
    'artist' : IDL.Text,
    'energy' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SharingPreferences = IDL.Record({
    'shareExpiration' : IDL.Opt(Timestamp),
    'allowPublicAccess' : IDL.Bool,
    'allowDownload' : IDL.Bool,
  });
  const DeckState = IDL.Record({
    'bpm' : IDL.Opt(IDL.Nat),
    'currentTrack' : IDL.Opt(TrackId),
    'isPlaying' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateBpmAdjustment' : IDL.Func(
        [TrackId, TrackId],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'connectToStreamingLibrary' : IDL.Func([StreamingLibrary], [], []),
    'deleteMix' : IDL.Func([MixId], [], []),
    'deleteTrack' : IDL.Func([TrackId], [], []),
    'getAllMixes' : IDL.Func([], [IDL.Vec(MixMetadata)], ['query']),
    'getAllMixesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MixMetadata)],
        ['query'],
      ),
    'getAllTracks' : IDL.Func([], [IDL.Vec(TrackMetadata)], ['query']),
    'getAllTracksForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TrackMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSharingPreferences' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SharingPreferences)],
        ['query'],
      ),
    'getStreamingLibraries' : IDL.Func(
        [],
        [IDL.Vec(StreamingLibrary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importTrack' : IDL.Func([TrackMetadata], [TrackId], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'ping' : IDL.Func([], [Timestamp], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDeckState' : IDL.Func([DeckState], [], []),
    'saveMix' : IDL.Func([MixMetadata], [MixId], []),
    'setSharingPreferences' : IDL.Func([SharingPreferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };